Sqlite3
volodyapopyk/newt pull request #27
Opened 2023-02-21 19:18 UTC by volodyapopyk

my last db homework

2023-02-22 18:48 UTC, acman requested changes

2023-02-22 18:48 UTC, acman commented on dbtask2
> +SELECT purchase.id, purchase.date, first_name, last_name FROM purchase, users
According to task `INNER JOIN` should be used here, like 
```suggestion
SELECT p.id, p.date, first_name, last_name
FROM users INNER JOIN purchases p on users.id = p.user_id;
```

2023-02-22 18:48 UTC, acman commented on dbtask3
> +SELECT 'http://users.'||users.id||'/', first_name, last_name,books.title
nit: it was mistake in task [thread](https://robotdreamscc.slack.com/archives/C04BLF231NX/p1676828262891219) So only `users.id` can be used here and below

2023-02-22 18:48 UTC, acman commented on dbtask3
> +LEFT JOIN purchase on users.id = purchase.user_id
nit: `INNER JOIN` can be used here as well or probably I have not enough testing data

2023-02-22 18:48 UTC, acman commented on dbtask5
> +WHERE books.author = 'Rowling' AND book_id > 3
why `book_id > 3` :)

2023-02-22 18:48 UTC, acman commented on dbtask7
> +order by books.author
I didn't get why there is so complex condition
```suggestion
SELECT books.author, COUNT(purchases.book_id) AS count_purchases, SUM(books.price) AS sales_amount
FROM purchases
INNER JOIN books ON purchases.book_id = books.id
GROUP BY books.author
```

2023-03-02 10:50 UTC, vhreb approved these changes
👍

2023-03-03 14:37 UTC, merged